language: c
sudo: false

branches:
  only:
    - master

cache: apt

matrix:
  include:
  - os: osx
    compiler: clang
    osx_image: xcode7.2

before_install:
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install openssl || true ; fi

script:
  - autoreconf -i
  - if [ $TRAVIS_OS_NAME == osx ] ; then ./configure --with-openssl=/usr/local/Cellar/openssl/* ; fi
  - make V=1

