language: c
dist: trusty
sudo: false

branches:
  only:
    - master

cache: apt

matrix:
  include:
  - os: linux
    compiler: gcc
  - os: osx
    compiler: clang
    osx_image: xcode8.3

before_install:
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install openssl || true ; fi

script:
  - autoreconf -i
  - if [ $TRAVIS_OS_NAME == osx ] ; then ./configure --with-openssl=/usr/local/Cellar/openssl/* ; fi
  - if [ $TRAVIS_OS_NAME == linux ] ; then ./configure ; fi
  - make V=1
  - make test
